export const UPDATE_ETH = "UPDATE_ETH"
export const UPDATE_UNI = "UPDATE_UNI"
export const UPDATE_LP = "UPDATE_LP"
export const UPDATE_INPUT = "UPDATE_INPUT"
export const UPDATE_OUTPUT = "UPDATE_OUTPUT"
export const UPDATE_EXPECT = "UPDATE_EXPECT"